# Generated by Django 3.2.8 on 2022-01-25 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='img2',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
        migrations.AddField(
            model_name='hotel',
            name='img3',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='img1',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
    ]
