# Generated by Django 3.2.8 on 2022-02-07 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_hotel_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='city',
            field=models.CharField(default='', max_length=75),
        ),
        migrations.AddField(
            model_name='hotel',
            name='country',
            field=models.CharField(default='', max_length=75),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
    ]
