# Generated by Django 3.2.8 on 2022-02-07 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_auto_20220207_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='img4',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
        migrations.AddField(
            model_name='hotel',
            name='img5',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
    ]
